import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";

const ubuntu = Ubuntu({
  weight : "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ colorScheme : "dark"}}>
      <body
      suppressHydrationWarning
      
      className={`${ubuntu.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme={"dark"}
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            {children}  
          </ClerkProvider>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
